Upgrade tutorial for 12.1.0.Final
infinispan/infinispan-server-tutorial pull request #5
Opened 2021-04-12 07:54 UTC by karesti

2021-04-12 07:54 UTC, karesti commented
@oraNod upgraded

2021-04-13 07:20 UTC, oraNod requested changes
Thanks, Katia. Sorry I missed this yesterday. Just a couple minor changes and I think it's good to go then.

2021-04-13 07:20 UTC, oraNod commented on README.adoc
>  .Credentials
```suggestion
```

2021-04-13 07:20 UTC, oraNod commented on README.adoc
> +By default, Infinispan Server *requires user authentication* and *authorization* is implicit since
```suggestion
By default, Infinispan Server requires user *authentication* and *authorization*.
```

2021-04-13 07:20 UTC, oraNod commented on README.adoc
> +12.1. *Creating a user named `admin` gives you administrative access to Infinispan Server.*
```suggestion
For the purposes of this tutorial, create a user named `admin` so you get administrative access to Infinispan Server.
```

2021-04-14 08:51 UTC, oraNod approved these changes
LGTM

2021-04-14 08:52 UTC, merged

2021-04-14 08:53 UTC, oraNod commented
Thanks @karesti I wasn't able to squash and merge though so maybe the git log won't be so clean...