Upgrade 12.1
infinispan/infinispan-server-tutorial pull request #6
Opened 2021-07-06 22:22 UTC by karesti

2021-07-07 08:26 UTC, oraNod requested changes

2021-07-07 08:26 UTC, oraNod commented on README.adoc
> +and on the Infinispan Server.
```suggestion
As before, configure the `weather` cache.

.org.infinispan.tutorial.db.DataSourceConnector
[source,java]
----
builder.remoteCache("weather").configurationURI(weatherCacheConfig); <1>
----
<1> Adds a cache named `weather` that uses the content of the 'weatherCacheConfig.xml' file.

Unlike the `temperature` cache, the `weather` cache stores complex Java objects and you will query 
the values. For this reason the serialization context needs to be registered on the client
and on Infinispan Server.
```

2021-07-07 08:26 UTC, oraNod commented on README.adoc
> +builder.remoteCache("temperature").configurationURI(temperatureCacheConfig);
```suggestion
builder.remoteCache("temperature").configurationURI(temperatureCacheConfig); <1>
```

2021-07-07 08:26 UTC, oraNod commented on README.adoc
> +Update the `connect()` method in the `DataSourceConnector` class add a `remoteCache("temperature")` as follows:
```suggestion
Update the `connect()` method in the `DataSourceConnector` class by adding a `remoteCache("temperature")` as follows:
```

2021-07-07 08:26 UTC, oraNod commented on README.adoc
> +- IDE such as Eclipse, Intellij
```suggestion
- IDE such as Eclipse or Intellij
```

2021-07-07 13:47 UTC, karesti commented
@oraNod commits squashed

2021-07-07 17:52 UTC, oraNod approved these changes
LGTM. Should we merge @karesti or do we need to hold off on something else?

2021-07-08 08:24 UTC, karesti commented
nothing else, just merge and I do the solution branch and I publish the website

2021-07-08 09:28 UTC, merged

2021-07-08 09:28 UTC, oraNod commented
thanks @karesti